### ISSUE TITLE
感谢使用 Pont，Pont 已经内置了自动化的Mocks数据生成的功能，提供轻量的Mocks服务

### ISSUE THREAD

**Issue by jasonHzq** [rmbf2e/react-mobx-scaffold#1]
如题

**Comment by superwf** [comment]
感谢分享pont。
刚使用pont的时候，有的地方会有使用pontFetch方法，但找不到从哪里引入的。
所以只使用了生成的baseClass。
经过一段时间pont的使用有一些地方做了针对自己项目的更改，后来越改越多偏的太多了。
所以没有提pr。
又造了一个类似pont的轮子起名叫ts-gear，在自己的几个项目里还挺好用。
